pub mod allocate;
pub mod assign_homes;
pub mod build_interference;
pub mod liveness;
pub mod patch;
pub mod rco;
pub mod select_instructions;
pub mod gen;
pub mod shrink;
//pub mod explicate_control;
pub mod clike;
mod frame;
mod x86;
